# Generated by Django 5.0 on 2023-12-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_cate1_post_cate2_post_cate3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
