# Generated by Django 5.0 on 2023-12-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedetail',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='recipeingred',
            old_name='post_id',
            new_name='post',
        ),
    ]
