# Generated by Django 5.0 on 2023-12-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_post_id_recipedetail_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetail',
            name='step',
            field=models.CharField(max_length=10),
        ),
    ]
